### ISSUE TITLE
NBA Roster Turnover is now included in the Awesome Streamlit Gallery

### ISSUE THREAD

**Issue by MarcSkovMadsen** [arvkevi/nba-roster-turnover#2]
Hi @arvkevi 

Thanks again for reaching out. Your app is now in the awesome-streamlit.org Gallery.

I took the liberty of refactoring it a bit. I hope it's ok? Otherwise let me know.

I learn a lot from these refactorings: Other data than normal, other coding styles than normal, using streamlit.

If you look at the updated code i've inserted my ideas for further improvements.

You can find it at http://awesome-streamlit.org/

![image](https://user-images.githubusercontent.com/42288570/67138653-fdba7a80-f246-11e9-9984-53a59694f80e.png)

**Comment by MarcSkovMadsen** [comment]
Hi @arvkevi 

If you would like to help your self, the streamlit community, streamlit.io, awesome-streamlit.org and me (in that order :-)) then you can by communicating that your app is now available in the awesome-streamlit.org Gallery.

Good places to post are

- https://discuss.streamlit.io/
- twitter.com
- linkedin.com

If you feel like it then please mention https://awesome-streamlit.org and maybe me

My social contact details are (if you need them)
- https://www.linkedin.com/in/marcskovmadsen/
- https://twitter.com/MarcSkovMadsen
- https://github.com/marcskovmadsen

Thanks

**Comment by MarcSkovMadsen** [comment]
I can see that you have some more awesome data and visualizations in your repository. Feel free to share as Streamlit App in the Gallery.

Thanks.

**Comment by arvkevi** [comment]
Thanks @MarcSkovMadsen do you mind if I update the app to incorporate your improvements?
